using SummerBreeze;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SummerBreeze
{
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct)]
    public class BreezeAutoGeneratedKeyTypeAttribute : System.Attribute
    {

        public SummerBreezeEnums.AutoGeneratedKeyType AutoGeneratedKeyType { get; private set; }

        public BreezeAutoGeneratedKeyTypeAttribute(SummerBreezeEnums.AutoGeneratedKeyType autogeneratedkeytype)
        {
            AutoGeneratedKeyType = autogeneratedkeytype;
        }
    }
}
