using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SummerBreeze
{
    public class BreezeEntityTypeMetadata
    {
        public string shortName { get; set; }
        public string @namespace { get; set; }

        private string _autoGeneratedKeyType = string.Empty;
        public string autoGeneratedKeyType { get { return "breeze.AutoGeneratedKeyType." + _autoGeneratedKeyType; } set { _autoGeneratedKeyType = value; } }

        public List<BreezeDataPropertyMetadata> dataProperties { get; set; }
        public List<BreezeNavigationPropertyMetadata> navigationProperties { get; set; }

    
    }

    
}
