using SummerBreeze;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SummerBreezeDemo.Models.DTO
{
    [BreezeLocalizable]
    [BreezeAutoGeneratedKeyType(SummerBreezeEnums.AutoGeneratedKeyType.Identity)]
    public class ManufacturerDTO
    {
        [Key]
        public Guid DtoId { get; set; }

        public string Name { get; set; }

        public Guid ObjectId { get; set; } //foreign key

        [BreezeNavigationProperty("NeedNavigation_ManufacturerDTO", "ObjectId")]
        public virtual NeedInversePropertiesDTO NeedInversePropertiesDTO { get; set; }
       

    }
}